theme: jekyll-theme-hacker
title: Zack's homepage
description: Bay Area Level 2 IT Technician
show_downloads: false
google_analytics: G-Y7HWYKD8KV
github:
  repository_name: Zack's homepage
  project_tagline: Bay Area Level 2 IT Technician
