theme: jekyll-theme-hacker
title: Zack's homepage
description: Come back soon to look at my current projects!
show_downloads: false
google_analytics:
github:
  repository_name: Zack's homepage
  project_tagline: Come back soon to look at my current projects!
